name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Google Maps, Geolocation, and Polylines packages
  google_maps_flutter: ^2.1.8
  geolocator: ^10.0.0
  flutter_polyline_points: ^1.0.0

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
